apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd01
  labels:
    app: httpd
  namespace: dev
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: httpd
    spec:
      containers:
        - name: httpd
          image: susigugh/httpdimg:1.3
  selector:
    matchLabels:
      app: httpd
